import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'

export default function Contact() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <h1>Contact page</h1>
      </div>
    </>
  )
}
